[project]
name = "yaya"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "adbutils[all]>=2.12.0",
    "fastapi[standard]>=0.121.3",
    "libsql>=0.1.11",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
]
