[project]
name = "yaya"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.121.3",
    "libsql-client>=0.3.1",
    "python-dotenv>=1.2.1",
]
